### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by woutervanerp** [callumacrae/vue-futurelink#10]
Love the idea of this plugin!
I got one problem, i don't know how to impement future-link.
Do i just replace all <router-link></router-link with   <futurelink></futurelink>?

Maybe a example would help :)

**Comment by markhalliwell** [comment]
https://github.com/callumacrae/vue-futurelink#usage

**Comment by callumacrae** [comment]
thanks @markhalliwell - totally missed this issue!
