### ISSUE TITLE
Update NPM release

### ISSUE THREAD

**Issue by markhalliwell** [callumacrae/vue-futurelink#14]
https://www.npmjs.com/package/vue-futurelink is severely outdated from current master.

Currently,  I have to do the following in `package.json`:

```js
"vue-futurelink": "git+https://git@github.com/callumacrae/vue-futurelink.git#master",
```

**Comment by markhalliwell** [comment]
Bump

**Comment by callumacrae** [comment]
Apologies! Looking at this now.

**Comment by callumacrae** [comment]
Released as 1.2.0 :)

**Comment by markhalliwell** [comment]
Thank you! 😄

**Comment by markhalliwell** [comment]
Did you happen to push to npm? Not seeing `1.2.0` here: https://www.npmjs.com/package/vue-futurelink?activeTab=versions

**Comment by callumacrae** [comment]
Whoops, not sure what happened there. Have published again!

It's not showing up in the website, but it's showing up in `npm info` now so I'm assuming it's a caching issue!

**Comment by markhalliwell** [comment]
Must have just been some caching as it's showing up now  😄 🎉 Thank you again!
